# ----------------
# Home Dashboard
# ----------------
postgresql:
  restart: always
  image: sameersbn/postgresql:9.4-11
  env_file: ./common.env
  ports:
    - "5432:5432"
  volumes:
    - /usr/local/var/postgres:/var/lib/postgresql

dashing:
  restart: always
  env_file: ./common.env
  build: electric_dashing/
  extends:
    file: electric_dashing/docker-compose.yml
    service: dashing
  log_driver: "json-file"
  links:
    - postgresql:postgres

homedash:
  restart: always
  build: homedash/
  env_file: ./common.env
  links:
    - postgresql:postgres
  ports:
    - 3031:3030

# ------------------
# usenet services
# ------------------
sabnzbd:
  image: timhaak/sabnzbd
  ports: 
    - 7777:8080
  volumes:
   - /usr/local/var/sabnzbd_config:/config
   - /mnt/media:/data
  restart: always

sonarr:
  build: sonarr/
  restart: always
  env_file: ./common.env
  ports:
    - 8989:8989
  volumes:
    - /mnt/media:/volumes/completed
    - /usr/local/var/sonarr_config:/config
    - /usr/local/var/sonarr_downloads:/downloads
    - /mnt/media/TV:/tv
    - /dev/rtc:/dev/rtc:ro
  links:
    - sabnzbd:sabnzbd

plex:
  image: linuxserver/plex
  restart: always
  env_file: ./common.env
  ports:
    - 32400:32400
  volumes:
    - /mnt/media:/data
    - /usr/local/var/plex/config:/config
  net: host

plexpy:
  image: linuxserver/plexpy
  restart: always
  env_file: ./common.env
  ports:
    - 8181:8181
  volumes:
    - /usr/local/var/plex/config/Library/Application Support/Plex Media Server/Logs/:/logs:ro
    - /usr/local/var/plexpy/config:/config
    - /etc/localtime:/etc/localtime:ro


# ------------------------
smokeping:
  image: linuxserver/smokeping
  restart: always
  env_file: ./common.env
  ports:
    - 8080:80
  volumes:
    - /usr/local/var/smokeping:/data
    - /usr/local/etc/smokeping:/config
