postgresql:
  restart: always
  image: sameersbn/postgresql:9.4-11
  env_file: ./common.env
  ports:
    - "5432:5432"
  volumes:
    - /usr/local/var/postgres:/var/lib/postgresql

dashing:
  env_file: ./common.env
  build: electric_dashing/
  extends:
    file: electric_dashing/docker-compose.yml
    service: dashing
  log_driver: "json-file"
  links:
  - postgresql:postgres

homedash:
  build: homedash/
  env_file: ./common.env
  links:
  - postgresql:postgres
  ports:
  - 3031:3030
