nginx:
  restart: always
  build: nginx/
  ports:
    - 80:80
    - 443:443
  links:
    - homedash:homedash
    - sabnzbd:sabnzbd
    - couchpotato:couchpotato
    - sonarr:sonarr
    - plexpy:plexpy
    - smokeping:smokeping
    - nzbget:nzbget
  volumes:
    - /usr/local/etc/nginx/ssl:/etc/nginx/ssl:ro
    - /usr/local/var/nginx/log:/var/log/nginx

# ----------------
# Home Dashboard
# ----------------
postgresql:
  restart: always
  image: sameersbn/postgresql:9.4-11
  env_file: ./common.env
  ports:
    - "5432:5432"
  volumes:
    - /usr/local/var/postgres:/var/lib/postgresql

dashing:
  restart: always
  env_file: ./common.env
  build: electric_dashing/
  extends:
    file: electric_dashing/docker-compose.yml
    service: dashing
  log_driver: "json-file"
  links:
    - postgresql:postgres

homedash:
  restart: always
  build: homedash/
  env_file: ./common.env
  links:
    - postgresql:postgres

# ------------------
# usenet services
# ------------------
sabnzbd:
  image: timhaak/sabnzbd
  volumes:
   - /usr/local/var/sabnzbd_config:/config
   - /mnt/media:/data
  restart: always

couchpotato:
  image: linuxserver/couchpotato
  restart: always
  env_file: ./common.env
  volumes:
    - /usr/local/var/couchpotato/config:/config
    - /usr/local/var/couchpotato/downloads:/downloads
    - /mnt/media/Movies:/movies
    - /etc/localtime:/etc/localtime:ro
  links:
    - sabnzbd:sabnzbd

nzbget:
  image: linuxserver/nzbget
  restart: always
  env_file: ./common.env
  volumes:
    - /opt/docker/nzbget/config:/config
    - /mnt/media2:/downloads
    - /etc/localtime:/etc/localtime:ro
  links:
    - sabnzbd:sabnzbd

sonarr:
  build: sonarr/
  restart: always
  env_file: ./common.env
  volumes:
    - /mnt/media:/volumes/completed
    - /usr/local/var/sonarr_config:/config
    - /usr/local/var/sonarr_downloads:/downloads
    - /mnt/media/TV:/tv
    - /dev/rtc:/dev/rtc:ro
  links:
    - sabnzbd:sabnzbd

plex:
  image: linuxserver/plex
  restart: always
  env_file: ./common.env
  ports:
    - 32400:32400
  volumes:
    - /mnt/media:/data
    - /usr/local/var/plex/config:/config
  net: host

plexpy:
  image: linuxserver/plexpy
  restart: always
  env_file: ./common.env
  volumes:
    - /usr/local/var/plex/config/Library/Application Support/Plex Media Server/Logs/:/logs:ro
    - /usr/local/var/plexpy/config:/config
    - /etc/localtime:/etc/localtime:ro


# ------------------------
smokeping:
  build: smokeping/
  restart: always
  env_file: ./common.env
  volumes:
    - /usr/local/var/smokeping:/data
    - /usr/local/etc/smokeping:/config
